### ISSUE TITLE
引入Page的页面，van-dialog的before-close绑定函数后，弹框只能关闭，不能打开了

### ISSUE THREAD

**Issue by xiaofei3062** [Pursue-LLL/miniprogram-turbo-setdata#2]
引入Page的页面，van-dialog的before-close绑定函数后，弹框只能关闭，不能打开了
代码片段如下：
<van-dialog width="80vw" close-on-click-overlay use-slot title="添加当事人" show="{{ showDialog }}" show-cancel-button before-close="{{dialogBeforeClose}}">内容</van-dialog>
Page({
data:{
showDialog :false,
dialogBeforeClose:()=>{}
},
onLoad(){
// 绑定函数
this.setData({
dialogBeforeClose:this.handleDialogBeforeClose
})
},
// dialog关闭之前
  handleDialogBeforeClose(action) {
    if (action !== "confirm") return true;
    const { name, sex, cardNo } = this.data.form2;
    let personList = JSON.parse(JSON.stringify(this.data.personList));
    if (!name) {
      wx.$utils.showToast("请填写当事人姓名");
      return false;
    }
    if (!sex) {
      wx.$utils.showToast("请填写当事人性别");
      return false;
    }
    if (!cardNo) {
      wx.$utils.showToast("请填写当事人证件号码");
      return false;
    }
    personList.push(this.data.form2);
    this.setData({
      personList,
      form2: {
        name: "",
        sex: "",
        cardNo: "",
        address: "",
        phone: "",
      },
    });
    return true;
  },
})

**Comment by xiaofei3062** [comment]
页面代码如下：
<van-dialog width="80vw" close-on-click-overlay use-slot title="添加当事人" show="{{ showDialog }}" show-cancel-button before-close="{{dialogBeforeClose}}">
    <view style="height: 24px"></view>
    <van-cell-group>
      <van-field label="姓名" required value="{{ form2.name }}" placeholder="姓名（必填）" border="{{ false }}" data-key="name" bind:input="handleInput2" />
      <van-field label="性别" required value="{{ form2.sex }}" placeholder="性别（必填）" border="{{ false }}" data-key="sex" bind:input="handleInput2" />
      <van-field label="证件号码" type="idcard" required value="{{ form2.cardNo }}" placeholder="证件号码（必填）" border="{{ false }}" data-key="cardNo" bind:input="handleInput2" />
      <van-field label="居住地址" value="{{ form2.address }}" placeholder="居住地址" border="{{ false }}" data-key="address" bind:input="handleInput2" />
      <van-field label="联系电话" type="number" value="{{ form2.phone }}" placeholder="联系电话" border="{{ false }}" data-key="phone" bind:input="handleInput2" />
    </van-cell-group>
  </van-dialog>

**Comment by xiaofei3062** [comment]
页面代码如下：
<van-dialog width="80vw" close-on-click-overlay use-slot title="添加当事人" show="{{ showDialog }}" show-cancel-button before-close="{{dialogBeforeClose}}">
    <view style="height: 24px"></view>
    <van-cell-group>
      <van-field label="姓名" required value="{{ form2.name }}" placeholder="姓名（必填）" border="{{ false }}" data-key="name" bind:input="handleInput2" />
      <van-field label="性别" required value="{{ form2.sex }}" placeholder="性别（必填）" border="{{ false }}" data-key="sex" bind:input="handleInput2" />
      <van-field label="证件号码" type="idcard" required value="{{ form2.cardNo }}" placeholder="证件号码（必填）" border="{{ false }}" data-key="cardNo" bind:input="handleInput2" />
      <van-field label="居住地址" value="{{ form2.address }}" placeholder="居住地址" border="{{ false }}" data-key="address" bind:input="handleInput2" />
      <van-field label="联系电话" type="number" value="{{ form2.phone }}" placeholder="联系电话" border="{{ false }}" data-key="phone" bind:input="handleInput2" />
    </van-cell-group>
  </van-dialog>

**Comment by xiaofei3062** [comment]
页面代码如下图：
![image](https://user-images.githubusercontent.com/51069900/202632927-eae5cff9-c386-476e-b6e9-646e00e0faeb.png)

**Comment by Pursue-LLL** [comment]
收到，我用 van 调试一下

**Comment by Pursue-LLL** [comment]
不能再打开的原因是，你关闭的时候没有将 showDialog 设置为 false，对于工具来说数据并未发生变化所以略过本次更新了。
遇到问题时建议开启日志选项，可自查大部分 Bug 原因。
 
  turboOptions: {
    useSyncData: true, // 是否需要在 setData 后同步获取新值（全局配置）
    // logNative: true,  // 是否输出原生表现日志，开启后会使用原生 setData 并输出耗时和次数，可用于对比优化效果
    logTimeConsuming:  true, // 是否输出优化后的 setData 耗时和次数
    logUpdatedData: true, // 是否输出本次 setData 被更新的数据(合并且 diff 后的)
    logDuplicateData: true, // 是否输出被筛选出的重复数据
  }

**Comment by xiaofei3062** [comment]
这个关闭是vant内部处理的，正常写的话是不需要从外部干预的，这种情况可以优化吗
